### ISSUE TITLE
Strange Space Usage

### ISSUE THREAD

**Issue by idontgetoutmuch** [Shimuuar/mwc-random-monad#1]
With

```
import System.Random.MWC.Monad
import Control.Monad
import Control.Monad.Primitive.Class

testUniform :: MonadPrim m => Int -> Rand m [Double]
testUniform n = replicateM (fromIntegral n) (uniformR (0,1))

n :: Int
n = 2 * 10^7

main :: IO ()
main = do
  xs <- runWithCreate (testUniform (fromIntegral n))
  print ((sum xs) / (fromIntegral n))
```

I get

```
~/Dropbox/Private/Stochastic $ ./TestMWCProb +RTS -s
0.5000367523944049
   1,132,289,656 bytes allocated in the heap
   2,431,628,448 bytes copied during GC
     693,925,992 bytes maximum residency (10 sample(s))
      44,003,224 bytes maximum slop
            1244 MB total memory in use (0 MB lost due to fragmentation)
```

On the other hand if I use `MT` in `random-fu`

```
import Data.Random.Source.PureMT
import Data.Random
import Control.Monad.State

testUniform :: MonadRandom m => Int -> m [Double]
testUniform n = replicateM (fromIntegral n) (sample stdUniform)

n :: Int
n = 2 * 10^7

test = do
  xs <- testUniform n
  return ((sum xs) / (fromIntegral n))

r = evalState test (pureMT 7)

main :: IO ()
main = do
  print r
```

I get

```
~/Dropbox/Private/Stochastic $ ./TestUniform +RTS -s
0.5000597098222788
  13,444,720,648 bytes allocated in the heap
       5,744,568 bytes copied during GC
          44,384 bytes maximum residency (2 sample(s))
          21,152 bytes maximum slop
               1 MB total memory in use (0 MB lost due to fragmentation)
```

Should I not use `MWC` in this way?

**Comment by Shimuuar** [comment]
That's very interesting. High memory use with mwc-random-monad is not surprising at all. `RandT IO` is basically `ReaderT (Gen ...) IO`. So it have to build full list in memory first. And random-u apparently builds list lazily. I wonder how do they achieve it.

**Comment by Shimuuar** [comment]
I looked a bit at random-fu's implementation. It's pure state monad so it can interleave generation of random numbers with folding them. It have to pay with performance mersenne twister's state is quite large (≈2.5kB). mwc-random uses PRNG with mutable state so it have to generate full list before it could start folding. There were some tricks for generating stream of random numbers using lazy ST. But I don't remember how to do it. So only reasonable option is to interleave folding and generation of random numbers manually.

So i'm closing issue.

**Comment by idontgetoutmuch** [comment]
Thanks very much for looking into this. I occasionally trip over everything working fine with MT and then switch to MWC and wonder why things no longer work. I still don't think we have a great story for RNGs in Haskell. One day...

**Comment by Shimuuar** [comment]
I're welcome. This use of lazyness is somewhat fragile and non-composable. For example should anything generate random number after list it will force whole list due to data dependency on PRNG state

``` haskell
test = do
  xs <- testUniform n
  x <- generateSomething -- forces xs spine (at least)
  return ((sum xs) / (fromIntegral n))
```

And yes good API for PRNG is thing of dreams so far. And inveting API which works well with both pure and stateful generators could be challenging I think
